#    TODO: cleanup this some are probably redundant or non-persistent
- name: Enable Remote Desktop
  ansible.windows.win_regedit:
    path: 'HKLM:\System\CurrentControlSet\Control\Terminal Server'
    name: fDenyTSConnections
    data: 0
    type: dword

- name: Enable Firewall Inbound Rules Group
  ansible.windows.win_shell: Enable-NetFirewallRule -DisplayGroup "{{ item }}"
  loop:
    - Remote Desktop
    - Windows Remote Management

#    - name: Use the plaintext WinRM transport and force it to use basic authentication
#      ansible.windows.win_shell: winrm set winrm/config/service '@{AllowUnencrypted="true"}'

- name: Remove all current pagefiles
  community.windows.win_pagefile:
    remove_all: true
    automatic: false
    state: absent

- name: Disable Hibernate Mode
  ansible.windows.win_command: powercfg -h off
  changed_when: false
  when: ansible_distribution is search("Microsoft Windows 10")

- name: Disable System Restore
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\Configuration Manager
    name: MaxSpace
    data: 0
    type: dword

- name: Disable Windows Search
  win_service:
    name: WSearch
    start_mode: disabled
    state: stopped

- name: Disable Windows Defender Real-time Protection
  win_command: powershell Set-MpPreference -DisableRealtimeMonitoring $true

- name: Disable NTFS Last Access Time Updates
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem
    name: NtfsDisableLastAccessUpdate
    data: 1
    type: dword

#    - name: Set Power Plan to High Performance
#      win_command: powercfg /s 8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c


- name: Install windows updates
  ansible.windows.win_updates:
    category_names:
      - CriticalUpdates
#      - SecurityUpdates
#      - Application
#      - Connectors
#      - DefinitionUpdates
#      - DeveloperKits
#      - FeaturePacks
#      - Guidance
#      - ServicePacks
#      - Tools
#      - UpdateRollups
#      - Updates
    reboot: true
    reboot_timeout: 10000
  register: windows_updates

- name: Windows reboot
  ansible.windows.win_reboot:
    reboot_timeout: 10000
  when: windows_updates.reboot_required and allow_windows_reboot_during_win_updates
