# roles/packages/tasks/main.yml
- name: Upgrade installed packages
  win_chocolatey:
    name: all
    state: latest

- name: Install multiple packages
  win_chocolatey:
    name: "{{ item }}"
    state: present
  loop: "{{ chocolatey_packages }}"


- name: M$ Store App update
  win_shell: Get-CimInstance -Namespace "Root\cimv2\mdm\dmmap" -ClassName "MDM_EnterpriseModernAppManagement_AppManagement01" | Invoke-CimMethod -MethodName UpdateScanMethod

